[2023-07-01T05:11:43.759+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_deps_3.get_sklearn scheduled__2023-06-30T00:00:00+00:00 [queued]>
[2023-07-01T05:11:43.765+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_deps_3.get_sklearn scheduled__2023-06-30T00:00:00+00:00 [queued]>
[2023-07-01T05:11:43.766+0000] {taskinstance.py:1308} INFO - Starting attempt 6 of 6
[2023-07-01T05:11:43.776+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-06-30 00:00:00+00:00
[2023-07-01T05:11:43.781+0000] {standard_task_runner.py:57} INFO - Started process 5480 to run task
[2023-07-01T05:11:43.783+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_deps_3', 'get_sklearn', 'scheduled__2023-06-30T00:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_deps.py', '--cfg-path', '/tmp/tmp3pppu7e0']
[2023-07-01T05:11:43.783+0000] {standard_task_runner.py:85} INFO - Job 166: Subtask get_sklearn
[2023-07-01T05:11:43.817+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_python_deps_3.get_sklearn scheduled__2023-06-30T00:00:00+00:00 [running]> on host 111d544596aa
[2023-07-01T05:11:43.876+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stare' AIRFLOW_CTX_DAG_ID='dag_with_python_deps_3' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-30T00:00:00+00:00'
[2023-07-01T05:11:43.877+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_deps.py", line 13, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-07-01T05:11:43.882+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dag_with_python_deps_3, task_id=get_sklearn, execution_date=20230630T000000, start_date=20230701T051143, end_date=20230701T051143
[2023-07-01T05:11:43.889+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 166 for task get_sklearn (No module named 'sklearn'; 5480)
[2023-07-01T05:11:43.915+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-01T05:11:43.927+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
