[2023-06-30T19:26:10.165+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_deps.get_sklearn manual__2023-06-30T19:26:09.484854+00:00 [queued]>
[2023-06-30T19:26:10.171+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_deps.get_sklearn manual__2023-06-30T19:26:09.484854+00:00 [queued]>
[2023-06-30T19:26:10.171+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-30T19:26:10.181+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-06-30 19:26:09.484854+00:00
[2023-06-30T19:26:10.185+0000] {standard_task_runner.py:57} INFO - Started process 1203 to run task
[2023-06-30T19:26:10.186+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_deps', 'get_sklearn', 'manual__2023-06-30T19:26:09.484854+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_deps.py', '--cfg-path', '/tmp/tmpafv_o3to']
[2023-06-30T19:26:10.186+0000] {standard_task_runner.py:85} INFO - Job 86: Subtask get_sklearn
[2023-06-30T19:26:10.220+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_python_deps.get_sklearn manual__2023-06-30T19:26:09.484854+00:00 [running]> on host 40ec38a36dc7
[2023-06-30T19:26:10.283+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stare' AIRFLOW_CTX_DAG_ID='dag_with_python_deps' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T19:26:09.484854+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-30T19:26:09.484854+00:00'
[2023-06-30T19:26:10.284+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_deps.py", line 13, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-06-30T19:26:10.290+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_deps, task_id=get_sklearn, execution_date=20230630T192609, start_date=20230630T192610, end_date=20230630T192610
[2023-06-30T19:26:10.299+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 86 for task get_sklearn (No module named 'sklearn'; 1203)
[2023-06-30T19:26:10.318+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-30T19:26:10.332+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
