[2023-07-07T15:34:10.601+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_imports_v5.get_data manual__2023-07-07T15:34:10.079222+00:00 [queued]>
[2023-07-07T15:34:10.607+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_imports_v5.get_data manual__2023-07-07T15:34:10.079222+00:00 [queued]>
[2023-07-07T15:34:10.607+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-07T15:34:10.618+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): get_data> on 2023-07-07 15:34:10.079222+00:00
[2023-07-07T15:34:10.623+0000] {standard_task_runner.py:57} INFO - Started process 582 to run task
[2023-07-07T15:34:10.625+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_imports_v5', 'get_data', 'manual__2023-07-07T15:34:10.079222+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/scrap_data.py', '--cfg-path', '/tmp/tmp46o5mg_c']
[2023-07-07T15:34:10.625+0000] {standard_task_runner.py:85} INFO - Job 66: Subtask get_data
[2023-07-07T15:34:10.657+0000] {task_command.py:410} INFO - Running <TaskInstance: test_imports_v5.get_data manual__2023-07-07T15:34:10.079222+00:00 [running]> on host d409bdcb9602
[2023-07-07T15:34:10.719+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_imports_v5' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-07T15:34:10.079222+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-07T15:34:10.079222+00:00'
[2023-07-07T15:34:10.720+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrap_data.py", line 23, in get_data
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2023-07-07T15:34:10.726+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=test_imports_v5, task_id=get_data, execution_date=20230707T153410, start_date=20230707T153410, end_date=20230707T153410
[2023-07-07T15:34:10.735+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 66 for task get_data (No module named 'selenium'; 582)
[2023-07-07T15:34:10.757+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-07T15:34:10.772+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
