[2023-06-30T01:59:01.222+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table manual__2023-06-30T01:56:59.206974+00:00 [queued]>
[2023-06-30T01:59:01.228+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_table manual__2023-06-30T01:56:59.206974+00:00 [queued]>
[2023-06-30T01:59:01.228+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-06-30T01:59:01.240+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-06-30 01:56:59.206974+00:00
[2023-06-30T01:59:01.247+0000] {standard_task_runner.py:57} INFO - Started process 368 to run task
[2023-06-30T01:59:01.249+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_table', 'manual__2023-06-30T01:56:59.206974+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpj4l85jim']
[2023-06-30T01:59:01.249+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask insert_into_table
[2023-06-30T01:59:01.281+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_table manual__2023-06-30T01:56:59.206974+00:00 [running]> on host 40ec38a36dc7
[2023-06-30T01:59:01.381+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stare' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-30T01:56:59.206974+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-30T01:56:59.206974+00:00'
[2023-06-30T01:59:01.382+0000] {sql.py:265} INFO - Executing: 
            insert into dag_runs(dt, dag_id) values ('2023-06-30', 'dag_with_postgres_operator_v02')
        
[2023-06-30T01:59:01.387+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-30T01:59:01.432+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-30T01:59:01.434+0000] {sql.py:375} INFO - Running statement: 
            insert into dag_runs(dt, dag_id) values ('2023-06-30', 'dag_with_postgres_operator_v02')
        , parameters: None
[2023-06-30T01:59:01.435+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-06-30, dag_with_postgres_operator_v02) already exists.

[2023-06-30T01:59:01.440+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_table, execution_date=20230630T015659, start_date=20230630T015901, end_date=20230630T015901
[2023-06-30T01:59:01.447+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 72 for task insert_into_table (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2023-06-30, dag_with_postgres_operator_v02) already exists.
; 368)
[2023-06-30T01:59:01.461+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-30T01:59:01.474+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
