[2023-07-01T03:42:07.929+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_deps.get_sklearn manual__2023-07-01T03:42:06.686225+00:00 [queued]>
[2023-07-01T03:42:07.935+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_deps.get_sklearn manual__2023-07-01T03:42:06.686225+00:00 [queued]>
[2023-07-01T03:42:07.935+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-07-01T03:42:07.945+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-07-01 03:42:06.686225+00:00
[2023-07-01T03:42:07.949+0000] {standard_task_runner.py:57} INFO - Started process 3871 to run task
[2023-07-01T03:42:07.952+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_deps', 'get_sklearn', 'manual__2023-07-01T03:42:06.686225+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_deps.py', '--cfg-path', '/tmp/tmpukxa1l7h']
[2023-07-01T03:42:07.952+0000] {standard_task_runner.py:85} INFO - Job 134: Subtask get_sklearn
[2023-07-01T03:42:07.984+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_python_deps.get_sklearn manual__2023-07-01T03:42:06.686225+00:00 [running]> on host 111d544596aa
[2023-07-01T03:42:08.041+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stare' AIRFLOW_CTX_DAG_ID='dag_with_python_deps' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-07-01T03:42:06.686225+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-01T03:42:06.686225+00:00'
[2023-07-01T03:42:08.041+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_deps.py", line 13, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-07-01T03:42:08.047+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_deps, task_id=get_sklearn, execution_date=20230701T034206, start_date=20230701T034207, end_date=20230701T034208
[2023-07-01T03:42:08.054+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 134 for task get_sklearn (No module named 'sklearn'; 3871)
[2023-07-01T03:42:08.082+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-01T03:42:08.097+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
