[2023-07-01T03:42:10.770+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_deps.get_sklearn manual__2023-07-01T03:40:08.463228+00:00 [queued]>
[2023-07-01T03:42:10.776+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_deps.get_sklearn manual__2023-07-01T03:40:08.463228+00:00 [queued]>
[2023-07-01T03:42:10.777+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-07-01T03:42:10.786+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-07-01 03:40:08.463228+00:00
[2023-07-01T03:42:10.790+0000] {standard_task_runner.py:57} INFO - Started process 3873 to run task
[2023-07-01T03:42:10.793+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_deps', 'get_sklearn', 'manual__2023-07-01T03:40:08.463228+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_deps.py', '--cfg-path', '/tmp/tmp134_fanr']
[2023-07-01T03:42:10.793+0000] {standard_task_runner.py:85} INFO - Job 135: Subtask get_sklearn
[2023-07-01T03:42:10.825+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_python_deps.get_sklearn manual__2023-07-01T03:40:08.463228+00:00 [running]> on host 111d544596aa
[2023-07-01T03:42:10.882+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stare' AIRFLOW_CTX_DAG_ID='dag_with_python_deps' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2023-07-01T03:40:08.463228+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-01T03:40:08.463228+00:00'
[2023-07-01T03:42:10.883+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_deps.py", line 13, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-07-01T03:42:10.888+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_deps, task_id=get_sklearn, execution_date=20230701T034008, start_date=20230701T034210, end_date=20230701T034210
[2023-07-01T03:42:10.896+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 135 for task get_sklearn (No module named 'sklearn'; 3873)
[2023-07-01T03:42:10.924+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-01T03:42:10.946+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
