[2023-07-01T05:44:03.184+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_python_deps_NEW.get_age scheduled__2023-06-29T04:05:00+00:00 [queued]>
[2023-07-01T05:44:03.194+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_python_deps_NEW.get_age scheduled__2023-06-29T04:05:00+00:00 [queued]>
[2023-07-01T05:44:03.194+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-07-01T05:44:03.207+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): get_age> on 2023-06-29 04:05:00+00:00
[2023-07-01T05:44:03.214+0000] {standard_task_runner.py:57} INFO - Started process 6073 to run task
[2023-07-01T05:44:03.216+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_python_deps_NEW', 'get_age', 'scheduled__2023-06-29T04:05:00+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_deps.py', '--cfg-path', '/tmp/tmppab9fnu1']
[2023-07-01T05:44:03.217+0000] {standard_task_runner.py:85} INFO - Job 181: Subtask get_age
[2023-07-01T05:44:03.264+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_python_deps_NEW.get_age scheduled__2023-06-29T04:05:00+00:00 [running]> on host 111d544596aa
[2023-07-01T05:44:03.354+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stare' AIRFLOW_CTX_DAG_ID='dag_python_deps_NEW' AIRFLOW_CTX_TASK_ID='get_age' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T04:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-29T04:05:00+00:00'
[2023-07-01T05:44:03.355+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_deps.py", line 25, in get_age
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-07-01T05:44:03.361+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_python_deps_NEW, task_id=get_age, execution_date=20230629T040500, start_date=20230701T054403, end_date=20230701T054403
[2023-07-01T05:44:03.369+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 181 for task get_age (No module named 'sklearn'; 6073)
[2023-07-01T05:44:03.389+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-01T05:44:03.413+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
