[2023-07-01T05:49:10.049+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_python_deps_NEW2.get_age manual__2023-07-01T05:49:08.708980+00:00 [queued]>
[2023-07-01T05:49:10.062+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_python_deps_NEW2.get_age manual__2023-07-01T05:49:08.708980+00:00 [queued]>
[2023-07-01T05:49:10.062+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-07-01T05:49:10.079+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): get_age> on 2023-07-01 05:49:08.708980+00:00
[2023-07-01T05:49:10.085+0000] {standard_task_runner.py:57} INFO - Started process 6180 to run task
[2023-07-01T05:49:10.088+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_python_deps_NEW2', 'get_age', 'manual__2023-07-01T05:49:08.708980+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_deps.py', '--cfg-path', '/tmp/tmpwqev_a8l']
[2023-07-01T05:49:10.088+0000] {standard_task_runner.py:85} INFO - Job 194: Subtask get_age
[2023-07-01T05:49:10.125+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_python_deps_NEW2.get_age manual__2023-07-01T05:49:08.708980+00:00 [running]> on host 111d544596aa
[2023-07-01T05:49:10.195+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stare' AIRFLOW_CTX_DAG_ID='dag_python_deps_NEW2' AIRFLOW_CTX_TASK_ID='get_age' AIRFLOW_CTX_EXECUTION_DATE='2023-07-01T05:49:08.708980+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-01T05:49:08.708980+00:00'
[2023-07-01T05:49:10.195+0000] {logging_mixin.py:149} INFO - /usr/local/bin
[2023-07-01T05:49:10.196+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_deps.py", line 28, in get_age
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-07-01T05:49:10.203+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_python_deps_NEW2, task_id=get_age, execution_date=20230701T054908, start_date=20230701T054910, end_date=20230701T054910
[2023-07-01T05:49:10.215+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 194 for task get_age (No module named 'sklearn'; 6180)
[2023-07-01T05:49:10.260+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-01T05:49:10.299+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
