[2023-06-29T23:06:42.717+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_2.third_task manual__2023-06-29T23:06:41.977527+00:00 [queued]>
[2023-06-29T23:06:42.725+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_2.third_task manual__2023-06-29T23:06:41.977527+00:00 [queued]>
[2023-06-29T23:06:42.725+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-29T23:06:42.742+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): third_task> on 2023-06-29 23:06:41.977527+00:00
[2023-06-29T23:06:42.749+0000] {standard_task_runner.py:57} INFO - Started process 3483 to run task
[2023-06-29T23:06:42.752+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_2', 'third_task', 'manual__2023-06-29T23:06:41.977527+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp0ninvxkv']
[2023-06-29T23:06:42.752+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask third_task
[2023-06-29T23:06:42.790+0000] {task_command.py:410} INFO - Running <TaskInstance: catchup_and_backfill_2.third_task manual__2023-06-29T23:06:41.977527+00:00 [running]> on host 3a20bfb037db
[2023-06-29T23:06:42.853+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stare' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_2' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T23:06:41.977527+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-29T23:06:41.977527+00:00'
[2023-06-29T23:06:42.853+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-06-29T23:06:42.854+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo hey, this is task3 and I run after task 1']
[2023-06-29T23:06:42.865+0000] {subprocess.py:86} INFO - Output:
[2023-06-29T23:06:42.867+0000] {subprocess.py:93} INFO - hey, this is task3 and I run after task 1
[2023-06-29T23:06:42.867+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-29T23:06:42.887+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=catchup_and_backfill_2, task_id=third_task, execution_date=20230629T230641, start_date=20230629T230642, end_date=20230629T230642
[2023-06-29T23:06:42.923+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-29T23:06:42.938+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
